# HTTP Server
[server]
	Address     = ":8199"
	ServerAgent = "extension-node"
	LogPath     = "/tmp/log/extension-node/server"
    RateInterval = 10
    RateBurst = 100
    # Crt = "path/.crt"
    # Key = "path/.key"
# Logger.
[logger]
    Path        = "/tmp/log/extension-node"
    Level       = "all"
    Stdout      = true

[mongo]
    Url = "mongodb://10.0.191.31:27017"
    Db = "admin"
    User = "admin"
    Pass = "123456"

[eth2]
    Url = "http://47.243.206.116:8545"

[sync]
    GetBlockContractStates = true
    BlockNumber = "0x46B87C"